### ISSUE TITLE
GnuCOBOL 3.2 breaks `Files-ReadAll`

### ISSUE THREAD

**Issue by Ituury** [meyfa/CobolCraft#209] opened 2024-12-26 19:36 UTC
Hey,

firstly, a very impressive effort.

I try to get it to run without docker, but I'm failing currently.
When cloning the repo and running `make run`
The following message is printed:

```txt
COB_PRE_LOAD=CBL_GC_SOCKET:COBOLCRAFT_UTIL ./cobolcraft
Loading registries
Failed to parse registries
```

I used `strace` to get some syscall outputs and the file is found as shown here:

```txt
openat(AT_FDCWD, "data/generated/reports/registries.json", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=451552, ...}) = 0
close(3)                                = 0
mmap(NULL, 20811776, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7d7d75088000
write(1, "Failed to parse registries\n", 27Failed to parse registries
) = 27
```

When I debugged some code (I'm not a COBOL expert at all), I noticed that the `DATA-BUFFER`  variable in the file `server.cob` is completely empty, after the `Files-ReadAll` procedure. 

Here are my system stats:

OS: Arch
Kernel: Linux 6.12.6-arch1-1
COBOL: cobc (GnuCOBOL) 3.2.0 (installed from the AUR)

If you need anything else, I'm happy to help.

**Comment by meyfa** [comment] 2024-12-26 20:04
I can reproduce this error when substituting `ubuntu:oracular` as the Docker base image, which also has GnuCOBOL 3.2. It seems pretty clear that the update from GnuCOBOL 3.1 to 3.2 breaks my file handling somehow. I'll investigate.

Maybe you're able to downgrade GnuCOBOL to 3.1.2 for now, which hopefully works as expected.

By the way, this repo has seen an enormous amount of interest today - would you happen to know why this is?

**Comment by Ituury** [comment] 2024-12-26 20:07
Ah, that explains it. And yes!
You're on the front page of Hacker News! Congrats

![image](https://github.com/user-attachments/assets/1bd5acf2-7acd-43ce-950b-924f87c6f34f)

**Comment by meyfa** [comment] 2024-12-26 20:13
That's awesome! Well, nice to see people find this project interesting.

**Comment by Ituury** [comment] 2024-12-26 20:13
Ah got the change in the in fileio.c of the compiler


Changelog: https://github.com/OCamlPro/gnucobol/blob/5086fdf05e340593eaeb30623b75d033ede69ecb/libcob/ChangeLog#L1147

And here the commit: https://github.com/OCamlPro/gnucobol/commit/a973461930a66489168837c4ba2988379319ffbd#diff-a05ba69ee0fed1374a543458ecb7055c1f1fc4dbbac1e928cbcf75ffff252a86R6966

**Comment by meyfa** [comment] 2024-12-26 20:44
Should be fixed with #210. Thanks a lot for bringing this to my attention and for looking into the cause. Please report how it goes.

**Closed** 2024-12-26 20:44 UTC

**Comment by Ituury** [comment] 2024-12-26 20:58
Works, thanks! You were a little faster than me. I also noticed the type size mismatch of the `LK-CLIENT-ID`. Two more minutes and a PR from me would have been open. Good work! :D

**Comment by meyfa** [comment] 2024-12-31 13:30
For future reference: The GitHub Actions tests are now run against both versions of GnuCOBOL (PR #228) and I also added a smoke test that starts and stops the server once to detect such crashes automatically (PR #229).
